updates

diff --git a/.github/workflows/slsa-builder-go.yml b/.github/workflows/slsa-builder-go.yml
--- a/.github/workflows/slsa-builder-go.yml
+++ b/.github/workflows/slsa-builder-go.yml
@@ -8,7 +8,8 @@ env:
   #TODO: let caller upload ?
   REGISTRY: ghcr.io
   BUILDER_BINARY: builder
-  BUILDER_REPOSITORY: laurentsimon/slsa-on-github@feat/herm
+  BUILDER_REPOSITORY: laurentsimon/slsa-on-github
+  BUILDER_REF: feat/herm
   BUILDER_URL: https://github.com/"$BUILDER_REPOSITORY"
 
 ###################################################################
@@ -48,6 +49,7 @@ jobs:
         with:
           fetch-depth: 0
           repository: "$BUILDER_REPOSITORY"
+          ref: "$BUILDER_REF"
 
       - name: Set up golang environment
         uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.3
@@ -66,7 +68,6 @@ jobs:
       #   with:
       #     to-state: enabled
 
-
       - name: Build builder
         shell: bash
         id: builder-gen
@@ -77,7 +78,7 @@ jobs:
             go build -mod=vendor -o "$BUILDER_BINARY"
             BUILDER_DIGEST=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
             echo "::set-output name=go-builder-sha256::$BUILDER_DIGEST"
-      
+
       - name: Upload the builder
         uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
         with:
@@ -90,7 +91,23 @@ jobs:
       go-binary-sha256: ${{ steps.build-gen.outputs.go-binary-sha256 }}
       go-binary-name: ${{ steps.build-gen.outputs.go-binary-name }}
     runs-on: ubuntu-latest
+    needs: builder
     steps:
+      - name: Download builder
+        uses: 'actions/download-artifact@v2'
+        with:
+          name: "$BUILDER_BINARY"
+
+      - name: Verify builder
+        env:
+          BUILDER_HASH: "${{ needs.builder.outputs.go-builder-sha256 }}"
+        run: |
+          set -euo pipefail
+          echo "hash of builder should be "$BUILDER_HASH"
+          DIGEST=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
+          echo "hash computed is: $DIGEST"
+          #TODO: compare hashes and fail if they are different.
+
       - name: Checkout the repository
         uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
         with:
@@ -108,10 +125,6 @@ jobs:
         run: |
           set -euo pipefail
           go mod vendor
-
-      - name: Download builder
-        uses: 'actions/download-artifact@v2'
-          name: ${{ needs.build.outputs.go-builder-sha256 }}
 
       # TODO(hermeticity) OS-level.
       # - name: Disable hermeticity
