updates

diff --git a/.github/workflows/slsa-builder-go.yml b/.github/workflows/slsa-builder-go.yml
--- a/.github/workflows/slsa-builder-go.yml
+++ b/.github/workflows/slsa-builder-go.yml
@@ -126,7 +126,7 @@ jobs:
           echo "hash computed is $COMPUTED_HASH"
 
           # Compare hashes. Explicit exit to be safe.
-          echo "de6a4ff08ea75e75ebac3fe52537c1ae04c1f0971d767475f0a43b4a50478227 $BUILDER_BINARY" | sha256sum --strict --check --status || echo "invalid hash" && exit -2
+          echo "$COMPUTED_HASH $BUILDER_BINARY" | sha256sum --strict --check --status || echo "invalid builder hash" && exit -2
     
           # Make the builder executable.
           chmod a+x "$BUILDER_BINARY"
